apiVersion: batch/v1
kind: Job
metadata:
  namespace: example05
  name: my-db-upgrade
  annotations:
    ±x
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "10"
      restartPolicy: Never
  backoffLimit: 2    
